version: 2.1

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.1.2
parameters:
  workingdir:
    type: string
    default: "100compute"
# our defined job, and its steps
jobs:
  setup:
    docker:
      - image: mkzielak/rackimage2:1 
    steps:
      - checkout # checkout code
      - run: # run a command
          name: Generate config
          command: |
            python3 ./scripts/main.py << pipeline.parameters.workingdir >>
      - continuation/continue:
          # use newly generated config to continue
          configuration_path: /root/project/.circleci/generated_config.yml 

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    jobs:
      - setup
